services:
  workspace: 
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    volumes:
      - ./:/usr/src/app
#    environment:
#      - PYTHONPATH=/usr/src/app
    tty: true