name: Create docker image by pull request

on:
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    if: github.event.pull_request.user.login == 'DerSteph'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest --doctest-modules --junitxml=test-results.xml --cov=com --cov-report=xml --cov-report=html
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-3.10
          path: test-results.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}


  build:
    if: github.event.pull_request.user.login == 'DerSteph'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - id: lowercase
      uses: Entepotenz/change-string-case-action-min-dependencies@v1.0.1
      with:
       string: ${{github.actor}}
    
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
       registry: ghcr.io
       username: ${{github.actor}}
       password: ${{secrets.GITHUB_TOKEN}}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ghcr.io/${{steps.lowercase.outputs.lowercase}}/kube-mdns:${{github.head_ref}}
