name: Create docker image by pull request

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    if: startsWith(github.head_ref, 'feature') && github.event.pull_request.user.login == 'DerSteph'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - id: lowercase
      uses: Entepotenz/change-string-case-action-min-dependencies@v1.0.1
      with:
       string: ${{github.actor}}
    
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
       registry: ghcr.io
       username: ${{github.actor}}
       password: ${{secrets.GITHUB_TOKEN}}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ghcr.io/${{steps.lowercase.outputs.lowercase}}/kube-mdns:${{github.head_ref}}
