name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
       registry: ghcr.io
       username: ${{github.actor}}
       password: ${{secrets.GITHUB_TOKEN}}

    - id: lowercase
      uses: Entepotenz/change-string-case-action-min-dependencies@v1.0.1
      with:
       string: ${{github.actor}}
    
    - name: Build and Push Docker image
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap
        docker buildx build -t ghcr.io/${{steps.lowercase.outputs.lowercase}}/kube-mdns:latest --platform linux/amd64,linux/arm64,linux/arm/v7 --push .
